name: Deploy Weather React App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Weather React App to Raspberry Pi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Build React App
        env:
          VITE_RAPID_API_KEY: ${{ secrets.VITE_RAPID_API_KEY }}
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD ssh -o StrictHostKeyChecking=no pi@$RASPBERRY_PI_IP << 'EOF'
            # Remove the old directory if it exists
            if [ -d "/var/www/html/weather_react_app" ]; then
              echo "Removing old directory..."
              rm -rf /var/www/html/weather_react_app
            fi

            # Create the directory if it doesn't exist
            echo "Creating new directory..."
            mkdir -p /var/www/html/weather_react_app

            # Exit from SSH to copy files
            exit
          EOF

      - name: Copy Built Files to Raspberry Pi
        env:
          RASPBERRY_PI_PASSWORD: ${{ secrets.RASPBERRY_PI_PASSWORD }}
          RASPBERRY_PI_IP: ${{ secrets.RASPBERRY_PI_IP }}
        run: |
          sshpass -p $RASPBERRY_PI_PASSWORD scp -o StrictHostKeyChecking=no -r dist/* pi@$RASPBERRY_PI_IP:/var/www/html/weather_react_app

      - name: Cleanup
        run: rm -rf ~/.ssh